services:
  - type: web
    name: flask-api-alunos
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgress:ZR5VLpYXn9LxfL7SSQxTbOPIoGolu3zd@dpg-d164m5adbo4c73d9deng-a.oregon-postgres.render.com/alunosdb_3fkm
